import { useEffect, useMemo, useState } from 'react';
import { api, downloadApi } from './api.js';
import { supabase } from './supabaseClient.js';
import { ArrowLeft, Building2, CalendarDays, ChevronRight, Download, FileText, IndianRupee, MessageCircle, Pencil, Plus, Search, Send, ShieldCheck, Trash2, Upload, Users, Wallet, X } from 'lucide-react';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const openingYear=2026, openingMonthIndex=6;
const validMonthsForYear=year=>year===openingYear?months.slice(openingMonthIndex):months;

function Toast({message,onClose}){useEffect(()=>{const t=setTimeout(onClose,3500);return()=>clearTimeout(t)},[message]);return <div className="toast">{message}<button onClick={onClose}><X size={16}/></button></div>}
function Field({label,error,children,wide}){return <label className={wide?'field wide':'field'}><span>{label}</span>{children}{error&&<small>{error}</small>}</label>}
function StudentForm({student,onClose,onSaved}){
 const [form,setForm]=useState(student||{full_name:'',class_year:'',admission_date:new Date().toISOString().slice(0,10),mobile:'',address:'',aadhar_number:'',total_fees:'',security_deposit:'',deposit_status:'Pending',deposit_received_date:'',deposit_refunded_date:''});
 const [file,setFile]=useState(); const [saving,setSaving]=useState(false); const [extracting,setExtracting]=useState(false); const [scanStatus,setScanStatus]=useState(''); const [error,setError]=useState('');
 const set=(k,v)=>setForm(current=>({...current,[k]:v}));
 async function selectAadhar(selectedFile){if(!selectedFile)return;setFile(selectedFile);setError('');setExtracting(true);setScanStatus(selectedFile.type==='application/pdf'?'Reading Aadhar PDF…':'Scanning Aadhar image…');try{const fd=new FormData();fd.append('aadhar_pdf',selectedFile);const details=await api('/api/aadhar/extract',{method:'POST',body:fd});setForm(current=>({...current,...(details.full_name&&{full_name:details.full_name}),...(details.aadhar_number&&{aadhar_number:details.aadhar_number}),...(details.address&&{address:details.address})}));const labels={full_name:'name',aadhar_number:'Aadhar number',address:'address'};const found=(details.found||[]).map(key=>labels[key]).filter(Boolean);setScanStatus(found.length?`Auto-filled ${found.join(', ')}. Please verify before saving.`:'No details were detected; please use a clearer image or enter them manually.');}catch(e){setScanStatus(e.message)}finally{setExtracting(false)}}
 async function submit(e){e.preventDefault();setSaving(true);setError('');try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v??''));if(file)fd.append('aadhar_pdf',file);await api(student?`/api/students/${student.id}`:'/api/students',{method:student?'PUT':'POST',body:fd});onSaved(student?'Student updated':'Student added');}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="overlay"><form className="modal" onSubmit={submit}>
  <div className="modal-head"><div><p className="eyebrow">STUDENT RECORD</p><h2>{student?'Edit student':'Add a new student'}</h2></div><button type="button" className="icon" onClick={onClose}><X/></button></div>
  {error&&<div className="error-banner">{error}</div>}
  <div className="form-grid">
   <Field label="Full name"><input required value={form.full_name} onChange={e=>set('full_name',e.target.value)} placeholder="Auto-filled from Aadhar document"/></Field>
   <Field label="Class / Year"><input required value={form.class_year} onChange={e=>set('class_year',e.target.value)} placeholder="e.g. B.Tech, 2nd Year"/></Field>
   <Field label="Admission date"><input required type="date" min="2026-07-01" value={form.admission_date||''} onChange={e=>set('admission_date',e.target.value)}/></Field>
   <Field label="Mobile number"><input required inputMode="numeric" maxLength="10" value={form.mobile} onChange={e=>set('mobile',e.target.value.replace(/\D/g,''))} placeholder="10-digit number"/></Field>
   <Field label="Aadhar number"><input required inputMode="numeric" maxLength="12" value={form.aadhar_number} onChange={e=>set('aadhar_number',e.target.value.replace(/\D/g,''))} placeholder="Auto-filled from Aadhar document"/></Field>
   <Field label="Total fees (₹)"><input required type="number" min="0" value={form.total_fees} onChange={e=>set('total_fees',e.target.value)} placeholder="60000"/></Field>
   <Field label="Security deposit (₹)"><input type="number" min="0" value={form.security_deposit??''} onChange={e=>set('security_deposit',e.target.value)} placeholder="e.g. 5000"/></Field>
   <Field label="Deposit status"><select value={form.deposit_status||'Pending'} onChange={e=>set('deposit_status',e.target.value)}><option>Pending</option><option>Held</option><option>Refunded</option></select></Field>
   <Field label="Deposit received date"><input type="date" min="2026-07-01" value={form.deposit_received_date||''} onChange={e=>set('deposit_received_date',e.target.value)}/></Field>
   {form.deposit_status==='Refunded'&&<Field label="Deposit refund date"><input type="date" min={form.deposit_received_date||'2026-07-01'} value={form.deposit_refunded_date||''} onChange={e=>set('deposit_refunded_date',e.target.value)}/></Field>}
   <Field label="Aadhar document"><div className={extracting?'file-input reading':'file-input'}><Upload size={17}/><span>{extracting?'Reading document…':file?.name|| (student?.aadhar_file?'Replace document':'Choose PDF or image')}</span><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={extracting} onChange={e=>selectAadhar(e.target.files[0])}/></div>{scanStatus&&<em className="scan-status">{scanStatus}</em>}</Field>
   <Field label="Permanent address" wide><textarea required value={form.address} onChange={e=>set('address',e.target.value)} placeholder="Auto-filled from Aadhar document" rows="3"/></Field>
  </div>
  <div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving||extracting}>{saving?'Saving…':extracting?'Reading Aadhar…':student?'Save changes':'Add student'}</button></div>
 </form></div>
}
function PaymentForm({student,onClose,onSaved}){
 const now=new Date(),admission=new Date(`${student.admission_date}T00:00:00`),currentYear=Math.max(now.getFullYear(),admission.getFullYear());
 const paymentMonthOptions=[];
 for(let y=admission.getFullYear();y<=currentYear+1;y++)validMonthsForYear(y).forEach(m=>{if(y>admission.getFullYear()||months.indexOf(m)>=admission.getMonth())paymentMonthOptions.push(`${m} ${y}`)});
 const initialDate=now>=admission?now:admission;const initialMonth=`${months[initialDate.getMonth()]} ${initialDate.getFullYear()}`;
 const [form,setForm]=useState({month:initialMonth,amount:'',payment_date:initialDate.toISOString().slice(0,10),mode:'UPI'});const [error,setError]=useState('');
 async function submit(e){e.preventDefault();try{await api(`/api/students/${student.id}/payments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});onSaved('Payment recorded')}catch(e){setError(e.message)}}
 return <div className="overlay"><form className="modal payment-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">FEE PAYMENT</p><h2>Record payment</h2><p className="muted">For {student.full_name} · admitted {admission.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</p></div><button type="button" className="icon" onClick={onClose}><X/></button></div>{error&&<div className="error-banner">{error}</div>}<div className="form-grid"><Field label="Fee month"><select required value={form.month} onChange={e=>setForm({...form,month:e.target.value})}>{paymentMonthOptions.map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Amount paid (₹)"><input autoFocus required type="number" min="1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Payment date"><input required type="date" min={student.admission_date} value={form.payment_date} onChange={e=>setForm({...form,payment_date:e.target.value})}/></Field><Field label="Payment mode"><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option>UPI</option><option>Cash</option><option>Bank transfer</option><option>Cheque</option></select></Field></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary">Record {form.amount?money(form.amount):'payment'}</button></div></form></div>
}

function ManagementApp({onLogout}){const [data,setData]=useState({students:[],stats:{}});const [query,setQuery]=useState('');const [selected,setSelected]=useState(null);const [form,setForm]=useState(null);const [payment,setPayment]=useState(false);const [toast,setToast]=useState('');const [loading,setLoading]=useState(true);async function load(){setLoading(true);try{setData(await api('/api/dashboard'));if(selected){const s=await api(`/api/students/${selected.id}`);setSelected(s)}}catch(e){setToast(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);async function openStudent(id){try{setSelected(await api(`/api/students/${id}`))}catch(e){setToast(e.message)}}const filtered=useMemo(()=>data.students.filter(s=>`${s.full_name} ${s.class_year}`.toLowerCase().includes(query.toLowerCase())),[data,query]);function saved(msg){setForm(null);setPayment(false);setToast(msg);load()}async function removeStudent(){if(!confirm(`Archive ${selected.full_name}? Their payment history will be retained.`))return;try{await api(`/api/students/${selected.id}`,{method:'DELETE'});setSelected(null);setToast('Student archived safely');load()}catch(e){setToast(e.message)}}async function removePayment(id){if(!confirm('Delete this payment entry?'))return;try{await api(`/api/payments/${id}`,{method:'DELETE'});setToast('Payment removed');load()}catch(e){setToast(e.message)}}return <div className="app"><aside><div className="brand"><div className="brandmark"><Building2/></div><div><strong>SWAMI</strong><span>HOSTEL LEDGER</span></div></div><nav><button className="active"><Users/>Students</button><button onClick={()=>downloadApi('/api/export','hostel-export.xlsx')}><FileText/>Excel export</button><button onClick={onLogout}>Logout</button></nav><div className="side-note"><span>2026–27</span><p>Single hostel workspace</p><i>All records are stored locally</i></div></aside><main><header><div><p className="eyebrow">OVERVIEW</p><h1>{selected?'Student profile':'Student records'}</h1></div><div className="head-actions">{selected?<button className="btn secondary" onClick={()=>setSelected(null)}><ArrowLeft size={18}/> All students</button>:<><button className="btn secondary" onClick={()=>downloadApi('/api/export','hostel-export.xlsx')}><Download size={18}/> Download Excel</button><button className="btn primary" onClick={()=>setForm('new')}><Plus size={18}/> Add student</button></>}</div></header>{selected?<Profile student={selected} onEdit={()=>setForm('edit')} onPayment={()=>setPayment(true)} onDelete={removeStudent} onDeletePayment={removePayment}/>:<Dashboard data={data} rows={filtered} query={query} setQuery={setQuery} loading={loading} openStudent={openStudent}/>}</main>{form&&<StudentForm student={form==='edit'?selected:null} onClose={()=>setForm(null)} onSaved={saved}/>} {payment&&<PaymentForm student={selected} onClose={()=>setPayment(false)} onSaved={saved}/>} {toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</div>}

function Dashboard({data,rows,query,setQuery,loading,openStudent}){const s=data.stats;return <><section className="stats"><Stat icon={<Users/>} label="Residents" value={s.students||0} note="Active students"/><Stat icon={<IndianRupee/>} label="Fees collected" value={money(s.total_paid)} note={`of ${money(s.total_fees)}`}/><Stat icon={<Wallet/>} label="Outstanding" value={money(s.pending)} note={s.pending?'Needs attention':'All settled'} accent={s.pending>0}/></section><section className="panel"><div className="panel-head"><div><h2>Current residents</h2><p>{rows.length} student{rows.length!==1?'s':''} in this view</p></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or class…"/></div></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Class / year</th><th>Fee status</th><th>Total paid</th><th>Pending amount</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty">Loading records…</td></tr>:rows.length?rows.map(s=><tr key={s.id} onClick={()=>openStudent(s.id)}><td><div className="student-cell"><div className="avatar">{s.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{s.full_name}</strong></div></div></td><td>{s.class_year}</td><td><span className={s.pending_amount<=0?'badge paid':'badge pending'}><i/>{s.pending_amount<=0?'Paid':'Pending'}</span></td><td className="numeric">{money(s.total_paid)}</td><td className="numeric strong">{money(s.pending_amount)}</td><td><ChevronRight size={18}/></td></tr>):<tr><td colSpan="6" className="empty"><Users size={34}/><strong>No students found</strong><span>Add your first resident to get started.</span></td></tr>}</tbody></table></div></section></>}
function Stat({icon,label,value,note,accent}) {return <div className={accent?'stat accent':'stat'}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function WhatsAppReminder({student:s}){
 const now=new Date(),admission=new Date(`${s.admission_date}T00:00:00`);
 const unpaid=[];
 for(let year=admission.getFullYear();year<=now.getFullYear();year++)validMonthsForYear(year).forEach(month=>{const index=months.indexOf(month);if(year===admission.getFullYear()&&index<admission.getMonth())return;const isAdmissionMonth=year===admission.getFullYear()&&index===admission.getMonth();const dueDate=isAdmissionMonth?admission:new Date(year,index,1);if(dueDate<=now){const paid=s.payments.some(p=>p.month===`${month} ${year}`);if(!paid)unpaid.push({month:`${month} ${year}`,due:dueDate.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})})}});
 const overdueList=unpaid.map(item=>`• ${item.month} — due on ${item.due}`).join('\n');
 const defaultMessage=`Namaste ${s.full_name},\n\nThis is a friendly rent reminder from SWAMI Hostel. Rent tracking starts from your admission date (${admission.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}). The first month's rent is due on admission, and each following month's rent is payable in advance on the 1st day.\n\nOur records show the following rent pending:\n${overdueList}\n\nKindly arrange payment at the earliest. If you have already paid, please ignore this reminder or share the payment confirmation with us.\n\nThank you,\nSWAMI Hostel`;
 const [message,setMessage]=useState(defaultMessage);
 useEffect(()=>setMessage(defaultMessage),[s.id,s.full_name,s.mobile,s.admission_date,s.pending_amount,s.payments.length]);
 const send=()=>window.open(`https://wa.me/91${s.mobile}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');
 return <section className="whatsapp-card"><div className="whatsapp-copy"><div className="whatsapp-title"><span><MessageCircle size={20}/></span><div><p>WHATSAPP RENT REMINDER</p><h2>Message advance-rent reminder</h2></div></div><p className="whatsapp-help">Monthly rent is due in advance on the 1st day of each month. Review the message before opening WhatsApp; nothing is sent automatically.</p><div className="whatsapp-recipient"><span>TO</span><strong>{s.full_name}</strong><i>+91 {s.mobile}</i></div></div>{unpaid.length>0?<div className="message-editor"><textarea rows="10" value={message} onChange={e=>setMessage(e.target.value)}/><div><small>{unpaid.length} overdue month{unpaid.length>1?'s':''} · {message.length} characters</small><button className="btn whatsapp-btn" onClick={send} disabled={!message.trim()}><Send size={17}/> Open in WhatsApp</button></div></div>:<div className="fees-clear"><span>✓</span><div><strong>No rent reminder needed</strong><p>All rent due up to today has been recorded as paid.</p></div></div>}</section>
}
function SecurityDeposit({student:s}){
 const status=s.deposit_status||'Pending';
 const date=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Not recorded';
 return <section className="deposit-card"><div className="deposit-icon"><ShieldCheck size={23}/></div><div className="deposit-main"><p>SECURITY DEPOSIT</p><strong>{money(s.security_deposit)}</strong><span>Tracked separately from monthly hostel fees</span></div><div className={`deposit-status ${status.toLowerCase()}`}><span>{status}</span><small>{status==='Refunded'?'Returned to student':status==='Held'?'Currently held by hostel':'Collection pending'}</small></div><div className="deposit-date"><span>Received</span><strong>{date(s.deposit_received_date)}</strong></div>{status==='Refunded'&&<div className="deposit-date"><span>Refunded</span><strong>{date(s.deposit_refunded_date)}</strong></div>}</section>
}
function Profile({student:s,onEdit,onPayment,onDelete,onDeletePayment}){
 const currentYear=new Date().getFullYear(),admission=new Date(`${s.admission_date}T00:00:00`);
 const paymentYears=s.payments.map(p=>Number(p.month.match(/\d{4}$/)?.[0])).filter(Boolean);
 const years=[...new Set([Math.max(currentYear,admission.getFullYear()),...paymentYears.filter(y=>y>=admission.getFullYear())])].sort((a,b)=>b-a);
 const [year,setYear]=useState(currentYear);
 const paidMonths=new Map();
 s.payments.forEach(p=>paidMonths.set(p.month,(paidMonths.get(p.month)||0)+p.amount));
 const visibleMonths=validMonthsForYear(year).filter(month=>year>admission.getFullYear()||months.indexOf(month)>=admission.getMonth());
 const yearTotal=visibleMonths.reduce((total,m)=>total+(paidMonths.get(`${m} ${year}`)||0),0);
 return <>
  <section className="profile-card"><div className="profile-top"><div className="profile-id"><div className="avatar large">{s.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h2>{s.full_name}</h2><p>{s.class_year} · Admitted {admission.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})} · Student #{String(s.id).padStart(4,'0')}</p></div></div><div className="profile-actions"><button className="btn secondary" onClick={onEdit}><Pencil size={17}/> Edit</button><button className="btn primary" onClick={onPayment}><Plus size={17}/> Record payment</button><button className="icon danger" onClick={onDelete} title="Archive student"><Trash2 size={19}/></button></div></div><div className="details-grid"><Detail label="Mobile" value={`+91 ${s.mobile}`}/><Detail label="Aadhar" value={`•••• •••• ${s.aadhar_number.slice(-4)}`}/><Detail label="Address" value={s.address}/><Detail label="Document" value={s.aadhar_file?<button className="document-link" onClick={()=>downloadApi(`/uploads/${s.aadhar_file}`,s.aadhar_file)}><FileText size={15}/> View Aadhar document</button>:'Not uploaded'}/></div></section>
  <section className="fee-grid"><div className="balance-card"><p>FEE BALANCE</p><strong>{money(s.pending_amount)}</strong><span>remaining of {money(s.total_fees)}</span><div className="progress"><i style={{width:`${Math.min(100,(s.total_paid/s.total_fees)*100||0)}%`}}/></div><small>{Math.round((s.total_paid/s.total_fees)*100||0)}% collected</small></div>
   <div className="month-card"><div className="month-head"><div><p>MONTH-WISE FEE STATUS</p><span>{money(yearTotal)} collected in {year} · Tracking from admission</span></div><select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y}>{y}</option>)}</select></div><div className="month-legend"><span><i className="paid-dot"/>Paid</span><span><i className="pending-dot"/>Pending</span></div><div className="months">{visibleMonths.map(m=>{const key=`${m} ${year}`,amount=paidMonths.get(key)||0,paid=amount>0;return <div key={m} className={paid?'month paid':'month pending'}><div><strong>{m.slice(0,3)}</strong><small>{paid?money(amount):'No payment'}</small></div><span>{paid?'Paid':'Pending'}</span></div>})}</div></div>
  </section>
  <SecurityDeposit student={s}/>
  <WhatsAppReminder student={s}/>
  <section className="panel payments"><div className="panel-head"><div><h2>Payment history</h2><p>{s.payments.length} recorded transaction{s.payments.length!==1?'s':''}</p></div></div><div className="table-wrap"><table><thead><tr><th>Month</th><th>Date paid</th><th>Mode</th><th>Amount</th><th></th></tr></thead><tbody>{s.payments.length?s.payments.map(p=><tr key={p.id}><td><strong>{p.month}</strong></td><td>{new Date(p.payment_date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</td><td><span className="mode">{p.mode||'—'}</span></td><td className="numeric strong">{money(p.amount)}</td><td><button className="icon subtle-danger" onClick={()=>onDeletePayment(p.id)}><Trash2 size={16}/></button></td></tr>):<tr><td colSpan="5" className="empty"><CalendarDays size={32}/><strong>No payments yet</strong><span>Record the first fee payment for this student.</span></td></tr>}</tbody></table></div></section>
 </>
}
function Detail({label,value}){return <div className="detail"><span>{label}</span><strong>{value}</strong></div>}
function Login({onAuthenticated}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');try{const {data,error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError||!data.session)throw new Error();await onAuthenticated(data.session)}catch{await supabase.auth.signOut().catch(()=>{});setError('Unable to sign in. Please try again.')}finally{setBusy(false)}}return <main className="auth-page"><form className="login-card" onSubmit={submit}><div className="brandmark"><Building2/></div><p className="eyebrow">OWNER ACCESS</p><h1>Sign in to SWAMI</h1><p className="muted">Use the hostel owner account. Public registration is not available.</p>{error&&<div className="error-banner">{error}</div>}<Field label="Email"><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Password"><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="btn primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></main>}

function App(){const [session,setSession]=useState(undefined);async function verify(next){if(!next){setSession(null);return}setSession(undefined);try{const result=await api('/api/auth/session');if(result?.authenticated!==true)throw new Error();setSession(next)}catch{await supabase.auth.signOut().catch(()=>{});setSession(null);throw new Error('Session verification failed')}}useEffect(()=>{if(!supabase){setSession(null);return}let active=true;supabase.auth.getSession().then(({data,error})=>{if(!active)return;if(error||!data.session){setSession(null);return}verify(data.session).catch(()=>{})}).catch(()=>active&&setSession(null));const {data:{subscription}}=supabase.auth.onAuthStateChange((event,next)=>{if(!active)return;if(event==='SIGNED_OUT'||!next)setSession(null)});return()=>{active=false;subscription.unsubscribe()}},[]);if(session===undefined)return <div className="auth-loading">Checking secure session…</div>;if(!supabase)return <div className="auth-loading">Authentication is not configured.</div>;if(!session)return <Login onAuthenticated={verify}/>;return <ManagementApp onLogout={()=>supabase.auth.signOut()}/>}

export default App;
