import express from 'express';
import cors from 'cors';
import multer from 'multer';
import path from 'node:path';
import fs from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { db, dataDir, uploadDir, studentRows } from './db.js';
import { excelPath, generateExcel, syncExcel } from './excel.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const app = express(); app.use(cors()); app.use(express.json()); app.use('/uploads', express.static(uploadDir));
const aadharTypes = new Map([['application/pdf','.pdf'],['image/jpeg','.jpg'],['image/png','.png'],['image/webp','.webp']]);
const aadharFilter = (_,file,cb) => cb(aadharTypes.has(file.mimetype)?null:new Error('Aadhar document must be a PDF, JPG, PNG, or WebP file'),aadharTypes.has(file.mimetype));
const storage = multer.diskStorage({ destination: uploadDir, filename: (_, f, cb) => cb(null, `${Date.now()}-${Math.random().toString(36).slice(2)}${aadharTypes.get(f.mimetype)}`) });
const upload = multer({ storage, limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: aadharFilter });
const extractUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: aadharFilter });
const runFile = promisify(execFile);
const bundledPython = 'C:\\Users\\jayha\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe';
const validate = s => { const e = {}; if (!s.full_name?.trim()) e.full_name='Full name is required'; if (!s.class_year?.trim()) e.class_year='Class / year is required'; if (!/^\d{10}$/.test(s.mobile||'')) e.mobile='Enter a valid 10-digit mobile number'; if (!s.address?.trim()) e.address='Address is required'; if (!/^\d{12}$/.test(s.aadhar_number||'')) e.aadhar_number='Enter a valid 12-digit Aadhar number'; if(!/^\d{4}-\d{2}-\d{2}$/.test(s.admission_date||'')||s.admission_date<'2026-07-01')e.admission_date='Admission date must be on or after 1 July 2026'; if (!(Number(s.total_fees)>=0)) e.total_fees='Enter a valid fee amount'; if (!(Number(s.security_deposit||0)>=0)) e.security_deposit='Enter a valid security deposit amount'; if(!['Pending','Held','Refunded'].includes(s.deposit_status||'Pending'))e.deposit_status='Choose a valid deposit status'; return e; };
const feeMonths=['January','February','March','April','May','June','July','August','September','October','November','December'];
function isOpenFeeMonth(value){const match=String(value).match(/^([A-Za-z]+)\s+(\d{4})$/);if(!match)return false;const month=feeMonths.findIndex(m=>m.toLowerCase()===match[1].toLowerCase());const year=Number(match[2]);return month>=0&&(year>2026||(year===2026&&month>=6));}
function feeMonthKey(value){const match=String(value).match(/^([A-Za-z]+)\s+(\d{4})$/);if(!match)return '';const index=feeMonths.findIndex(m=>m.toLowerCase()===match[1].toLowerCase());return index<0?'':`${match[2]}-${String(index+1).padStart(2,'0')}`;}

app.get('/api/dashboard', (_, res) => { const students=studentRows(); const fees=db.prepare('SELECT COALESCE(SUM(total_fees),0) n FROM students').get().n; const paid=db.prepare('SELECT COALESCE(SUM(amount),0) n FROM payments').get().n; res.json({students,stats:{students:students.length,total_fees:fees,total_paid:paid,pending:Math.max(fees-paid,0)}}); });
app.post('/api/aadhar/extract', extractUpload.single('aadhar_pdf'), async(req,res,next)=>{if(!req.file)return res.status(400).json({error:'Choose an Aadhar document first'});const id=crypto.randomUUID();const tempPath=path.join(dataDir,`extract-${id}${aadharTypes.get(req.file.mimetype)}`);const normalizedPath=path.join(dataDir,`extract-${id}-ocr.png`);const textPath=path.join(dataDir,`extract-${id}.txt`);try{fs.writeFileSync(tempPath,req.file.buffer);const python=process.env.PYTHON_PATH||(fs.existsSync(bundledPython)?bundledPython:'python');let parsePath=tempPath;if(req.file.mimetype!=='application/pdf'){await runFile(python,[path.join(root,'server','prepare_aadhar_image.py'),tempPath,normalizedPath],{timeout:20000,maxBuffer:1024*1024});const {stdout:ocrText}=await runFile('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(root,'server','ocr_image.ps1'),'-ImagePath',normalizedPath],{timeout:30000,maxBuffer:2*1024*1024});fs.writeFileSync(textPath,ocrText,'utf8');parsePath=textPath;}const {stdout}=await runFile(python,[path.join(root,'server','extract_aadhar.py'),parsePath],{timeout:20000,maxBuffer:1024*1024});const result=JSON.parse(stdout);res.json(result);}catch(e){let message='Could not read this document. Try a clearer, upright image or enter the details manually.';try{const parsed=JSON.parse(e.stdout||'{}');if(parsed.error)message=parsed.error;}catch{}res.status(422).json({error:message});}finally{[tempPath,normalizedPath,textPath].forEach(file=>fs.rmSync(file,{force:true}));}});
app.get('/api/students/:id', (req,res) => { const student=db.prepare('SELECT s.*,COALESCE(SUM(p.amount),0) total_paid FROM students s LEFT JOIN payments p ON p.student_id=s.id WHERE s.id=? GROUP BY s.id').get(req.params.id); if(!student)return res.status(404).json({error:'Student not found'}); student.pending_amount=Math.max(student.total_fees-student.total_paid,0); student.payments=db.prepare('SELECT * FROM payments WHERE student_id=? ORDER BY payment_date DESC,id DESC').all(req.params.id); res.json(student); });
app.post('/api/students', upload.single('aadhar_pdf'), (req,res,next) => { try { const errors=validate(req.body); if(Object.keys(errors).length){if(req.file)fs.unlinkSync(req.file.path);return res.status(400).json({errors});} const r=db.prepare('INSERT INTO students(full_name,class_year,mobile,address,aadhar_number,admission_date,aadhar_file,total_fees,security_deposit,deposit_status,deposit_received_date,deposit_refunded_date) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(req.body.full_name.trim(),req.body.class_year.trim(),req.body.mobile,req.body.address.trim(),req.body.aadhar_number,req.body.admission_date,req.file?.filename||null,Number(req.body.total_fees),Number(req.body.security_deposit||0),req.body.deposit_status||'Pending',req.body.deposit_received_date||null,req.body.deposit_refunded_date||null); syncExcel(); res.status(201).json({id:r.lastInsertRowid}); } catch(e){next(e);} });
app.put('/api/students/:id', upload.single('aadhar_pdf'), (req,res,next) => { try { const old=db.prepare('SELECT * FROM students WHERE id=?').get(req.params.id); if(!old)return res.status(404).json({error:'Student not found'}); const errors=validate(req.body); if(Object.keys(errors).length)return res.status(400).json({errors}); const file=req.file?.filename||old.aadhar_file; db.prepare('UPDATE students SET full_name=?,class_year=?,mobile=?,address=?,aadhar_number=?,admission_date=?,aadhar_file=?,total_fees=?,security_deposit=?,deposit_status=?,deposit_received_date=?,deposit_refunded_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.full_name.trim(),req.body.class_year.trim(),req.body.mobile,req.body.address.trim(),req.body.aadhar_number,req.body.admission_date,file,Number(req.body.total_fees),Number(req.body.security_deposit||0),req.body.deposit_status||'Pending',req.body.deposit_received_date||null,req.body.deposit_refunded_date||null,req.params.id); if(req.file&&old.aadhar_file)fs.rm(path.join(uploadDir,old.aadhar_file),{force:true},()=>{}); syncExcel(); res.json({ok:true}); } catch(e){next(e);} });
app.delete('/api/students/:id', (req,res,next) => { try { const tx=db.transaction(id=>{ const s=db.prepare('SELECT * FROM students WHERE id=?').get(id); if(!s)throw Object.assign(new Error('Student not found'),{status:404}); const pays=db.prepare('SELECT * FROM payments WHERE student_id=?').all(id); const total=pays.reduce((a,p)=>a+p.amount,0); db.prepare('INSERT INTO archived_students(original_student_id,full_name,class_year,mobile,address,aadhar_number,admission_date,total_fees,security_deposit,deposit_status,deposit_received_date,deposit_refunded_date,total_paid,pending_amount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(s.id,s.full_name,s.class_year,s.mobile,s.address,s.aadhar_number,s.admission_date,s.total_fees,s.security_deposit,s.deposit_status,s.deposit_received_date,s.deposit_refunded_date,total,Math.max(s.total_fees-total,0)); const ins=db.prepare('INSERT INTO archived_payments(original_payment_id,original_student_id,student_name,month,amount,payment_date,mode) VALUES(?,?,?,?,?,?,?)'); pays.forEach(p=>ins.run(p.id,s.id,s.full_name,p.month,p.amount,p.payment_date,p.mode)); db.prepare('DELETE FROM payments WHERE student_id=?').run(id); db.prepare('DELETE FROM students WHERE id=?').run(id); return s; }); const s=tx(req.params.id); if(s.aadhar_file)fs.rm(path.join(uploadDir,s.aadhar_file),{force:true},()=>{}); syncExcel(); res.json({ok:true,archived:true}); } catch(e){next(e);} });
app.post('/api/students/:id/payments', (req,res,next) => { try { const student=db.prepare('SELECT id,admission_date FROM students WHERE id=?').get(req.params.id);if(!student)return res.status(404).json({error:'Student not found'}); const {month,amount,payment_date,mode}=req.body; if(!month||!payment_date||!(Number(amount)>0))return res.status(400).json({error:'Month, date, and a positive amount are required'}); const admissionMonth=student.admission_date.slice(0,7);if(!isOpenFeeMonth(month)||feeMonthKey(month)<admissionMonth||payment_date<student.admission_date)return res.status(400).json({error:`Payments can only be recorded from the admission date (${student.admission_date}) onward`}); const r=db.prepare('INSERT INTO payments(student_id,month,amount,payment_date,mode) VALUES(?,?,?,?,?)').run(req.params.id,month,Number(amount),payment_date,mode||null); syncExcel(); res.status(201).json({id:r.lastInsertRowid}); } catch(e){next(e);} });
app.delete('/api/payments/:id', (req,res) => { const r=db.prepare('DELETE FROM payments WHERE id=?').run(req.params.id); syncExcel(); res.status(r.changes?200:404).json(r.changes?{ok:true}:{error:'Payment not found'}); });
app.get('/api/export', async(_,res,next)=>{try{await generateExcel();res.download(excelPath,'hostel-master.xlsx');}catch(e){next(e);}});
app.use((e,req,res,next)=>{console.error(e);if(e.code==='SQLITE_CONSTRAINT_UNIQUE')return res.status(409).json({error:'This Aadhar number is already registered'});res.status(e.status||400).json({error:e.message||'Something went wrong'});});
if(fs.existsSync(path.join(root,'dist'))){app.use(express.static(path.join(root,'dist')));app.get('/{*splat}',(req,res)=>res.sendFile(path.join(root,'dist','index.html')));}
const port=process.env.PORT||4000; if(process.env.NODE_ENV!=='test')app.listen(port,()=>{syncExcel();console.log(`SWAMI running at http://localhost:${port}`);});
export default app;
